# Generated by Django 4.2.3 on 2023-07-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='reservation',
        ),
    ]
