# Generated by Django 4.2.3 on 2023-07-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_trip_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('file', models.URLField(blank=True, max_length=1000)),
                ('type', models.CharField(choices=[('Dining', 'Dining'), ('Hotel', 'Hotel'), ('Transportation', 'Transportation'), ('Day Trip', 'Day Trip'), ('Museum', 'Museum'), ('Site Seeing', 'Site Seeing'), ('Tour', 'Tour'), ('Other', 'Other')], max_length=150)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.trip')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
